name: Build luci-app-webdroidx

on:
  workflow_dispatch:

jobs:
  build:
    name: Build WebDroidX Package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - master
          - 23.05.5
        arch:
          - x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build packages
        uses: openwrt/gh-action-sdk@main
        with:
          arch: ${{ matrix.arch }}-${{ matrix.release }}
          packages: luci-app-webdroidx
          index: false
          no_refresh_check: true
          
      - name: Find package files
        run: |
          find . -name "*luci-app-webdroidx*.ipk" -type f
          find . -name "*luci-app-webdroidx*.apk" -type f
          
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-webdroidx-${{ matrix.arch }}-${{ matrix.release }}
          path: |
            **/*luci-app-webdroidx*.ipk
            **/*luci-app-webdroidx*.apk
          if-no-files-found: error

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Get package info
        id: get_info
        run: |
          PKG_VERSION="1.0.$(date +'%y%m%d')"
          echo "version=$PKG_VERSION" >> $GITHUB_OUTPUT
          
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release_tag="${{ steps.get_info.outputs.version }}"
          release_body="# 🚀 luci-app-webdroidx for OpenWRT

          ## 📦 Release Version: \`${{ steps.get_info.outputs.version }}\`
          
          ### 🌟 Features:
          - WebDroidX functionality for OpenWRT
          - LuCI web interface integration
          - Easy installation and configuration"
          
          if ! gh release view "$release_tag" >/dev/null 2>&1; then
            gh release create "$release_tag" \
              --title "luci-app-webdroidx-$(date +'%y%m%d')" \
              --notes "$release_body"
          fi
          
      - name: Upload packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for pkg_file in $(find ./artifacts -name "*.ipk" -o -name "*.apk" -type f); do
            gh release upload ${{ steps.get_info.outputs.version }} "$pkg_file" --clobber
          done
