name: Build luci-app-webdroidx

on:
  workflow_dispatch:

jobs:
  build:
    name: Build WebDroidX Package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - master
          - 23.05.5
        arch:
          - x86_64

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build packages
      uses: openwrt/gh-action-sdk@main
      with:
        arch: ${{ matrix.arch }}-${{ matrix.release }}
        packages: luci-app-webdroidx
        index: false
        no_refresh_check: true

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-webdroidx-${{ matrix.arch }}-${{ matrix.release }}
        path: bin/packages/*/base/luci-app-webdroidx*.ipk
        if-no-files-found: error

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/packages/*/base/luci-app-webdroidx*.ipk
